import type { SpaceMission } from '@/types';

// Mock missions data - in a real app, this would come from an API
export function getMockMissions(): SpaceMission[] {
  return [
    {
      id: 'artemis-2',
      name: 'Artemis II',
      description: 'First crewed mission of the Artemis program. Four astronauts will fly around the Moon on a 10-day mission, traveling approximately 4,600 miles beyond the far side.',
      status: 'planned',
      type: 'crewed',
      startDate: '2025-09-01',
      agency: 'NASA',
      crew: [
        { id: 'c1', name: 'Reid Wiseman', role: 'Commander', agency: 'NASA', nationality: 'USA' },
        { id: 'c2', name: 'Victor Glover', role: 'Pilot', agency: 'NASA', nationality: 'USA' },
        { id: 'c3', name: 'Christina Koch', role: 'Mission Specialist', agency: 'NASA', nationality: 'USA' },
        { id: 'c4', name: 'Jeremy Hansen', role: 'Mission Specialist', agency: 'CSA', nationality: 'Canada' },
      ],
      objectives: [
        'First crewed Orion flight beyond Low Earth Orbit',
        'Test life support systems with crew',
        'Demonstrate SLS and Orion systems',
        'Verify trajectory and communications',
      ],
      progress: 75,
    },
    {
      id: 'exp-70',
      name: 'Expedition 70',
      description: 'Long-duration mission aboard the International Space Station conducting hundreds of experiments in biology, physics, and Earth science.',
      status: 'in-progress',
      type: 'crewed',
      startDate: '2023-09-27',
      endDate: '2024-04-01',
      agency: 'NASA/Roscosmos',
      crew: [
        { id: 'e1', name: 'Jasmin Moghbeli', role: 'Commander', agency: 'NASA', nationality: 'USA' },
        { id: 'e2', name: 'Andreas Mogensen', role: 'Flight Engineer', agency: 'ESA', nationality: 'Denmark' },
        { id: 'e3', name: 'Satoshi Furukawa', role: 'Flight Engineer', agency: 'JAXA', nationality: 'Japan' },
        { id: 'e4', name: 'Konstantin Borisov', role: 'Flight Engineer', agency: 'Roscosmos', nationality: 'Russia' },
      ],
      objectives: [
        'Conduct microgravity research',
        'Maintain station systems',
        'Support commercial crew operations',
        'Perform spacewalks as needed',
      ],
      progress: 85,
    },
    {
      id: 'europa-clipper',
      name: 'Europa Clipper',
      description: 'NASA mission to study Jupiter\'s icy moon Europa and investigate whether it has conditions suitable for life.',
      status: 'in-progress',
      type: 'robotic',
      startDate: '2024-10-14',
      endDate: '2030-04-01',
      agency: 'NASA',
      objectives: [
        'Characterize Europa\'s ice shell and ocean',
        'Map surface composition and geology',
        'Search for signs of habitability',
        'Select landing sites for future missions',
      ],
      progress: 15,
    },
    {
      id: 'mars-sample-return',
      name: 'Mars Sample Return',
      description: 'Joint NASA-ESA mission to return samples collected by the Perseverance rover to Earth.',
      status: 'planned',
      type: 'robotic',
      startDate: '2028-01-01',
      agency: 'NASA/ESA',
      objectives: [
        'Launch Sample Retrieval Lander',
        'Transfer samples to Mars Ascent Vehicle',
        'Return samples to Earth orbit',
        'Retrieve samples for analysis',
      ],
      progress: 35,
    },
    {
      id: 'dragonfly',
      name: 'Dragonfly',
      description: 'NASA mission to send a rotorcraft lander to Saturn\'s moon Titan to study prebiotic chemistry and habitability.',
      status: 'planned',
      type: 'robotic',
      startDate: '2028-07-01',
      agency: 'NASA',
      objectives: [
        'Search for prebiotic chemical processes',
        'Investigate methane cycle on Titan',
        'Characterize habitability of Titan',
        'Explore diverse surface locations',
      ],
      progress: 25,
    },
    {
      id: 'psyche',
      name: 'Psyche',
      description: 'NASA mission to explore asteroid 16 Psyche, thought to be the exposed metallic core of an early planet.',
      status: 'in-progress',
      type: 'robotic',
      startDate: '2023-10-13',
      endDate: '2029-08-01',
      agency: 'NASA',
      objectives: [
        'Determine if Psyche is a core',
        'Map surface elemental composition',
        'Characterize topography',
        'Determine relative ages of surface regions',
      ],
      progress: 20,
    },
    {
      id: 'lunar-gateway',
      name: 'Lunar Gateway',
      description: 'International space station in lunar orbit that will serve as a hub for lunar exploration.',
      status: 'planned',
      type: 'crewed',
      startDate: '2025-11-01',
      agency: 'NASA/ESA/JAXA/CSA',
      objectives: [
        'Establish first lunar orbit space station',
        'Support Artemis surface missions',
        'Enable deep space research',
        'Serve as staging point for Mars missions',
      ],
      progress: 40,
    },
    {
      id: 'chandrayaan-4',
      name: 'Chandrayaan-4',
      description: 'ISRO lunar sample return mission to collect and return Moon samples to Earth.',
      status: 'planned',
      type: 'robotic',
      startDate: '2027-01-01',
      agency: 'ISRO',
      objectives: [
        'Land on lunar surface',
        'Collect surface samples',
        'Launch samples to lunar orbit',
        'Return samples to Earth',
      ],
      progress: 20,
    },
  ];
}

export function getMockMissionStats() {
  return {
    activeMissions: 3,
    plannedMissions: 5,
    completedMissions: 8,
    crewInSpace: 11,
    agencies: ['NASA', 'ESA', 'JAXA', 'Roscosmos', 'ISRO', 'CSA', 'CNSA'],
  };
}
